packages:
  common: !include esphome_meshscope_common.yaml

esphome:
  name: meshscope-c5
  friendly_name: MeshScope C5

esp32:
  board: esp32-c5-devkitc-1
  variant: esp32c5
  flash_size: 8MB
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_XTAL_FREQ_48: "y"
      CONFIG_HTTPD_MAX_REQ_HDR_LEN: "2048"
      CONFIG_HTTPD_MAX_URI_LEN: "512"
      CONFIG_LWIP_MAX_SOCKETS: "12"
      CONFIG_MBEDTLS_EXTERNAL_MEM_ALLOC: "y"
      CONFIG_MBEDTLS_DYNAMIC_BUFFER: "y"
      CONFIG_ESP_TLS_INSECURE: "y"
      CONFIG_ESP_TLS_SKIP_SERVER_CERT_VERIFY: "y"
      CONFIG_SPIRAM_USE_MALLOC: "y"
      CONFIG_SPIRAM_MALLOC_ALWAYSINTERNAL: "0"
      CONFIG_SPIRAM_MALLOC_RESERVE_INTERNAL: "65536"
      CONFIG_SPIRAM_TRY_ALLOCATE_WIFI_LWIP: "y"

psram:
  mode: quad
  speed: 80MHz
  ignore_not_found: false
