#!/usr/bin/env python3
"""Generate deterministic gzip-compressed MeshScope assets for ESPHome."""

from __future__ import annotations

import argparse
import gzip
import hashlib
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
WEB_ROOT = ROOT / "mesh_web"
OUTPUT = ROOT / "esphome_includes" / "meshscope_web_assets.h"
SCRIPT_NAMES = (
    "refresh-state.js",
    "connection-mode.js",
    "node-restart-state.js",
    "detail-data.js",
    "topology-layout.js",
    "topology-renderer.js",
    "topology-lock-state.js",
    "mqtt-parent-steering-state.js",
    "linksys-normalize.js",
    "workspace.js",
    "app.js",
)
SOURCE_NAMES = ("index.html", "styles.css", *SCRIPT_NAMES)


def symbol(name: str) -> str:
    return "asset_" + "".join(char if char.isalnum() else "_" for char in name)


def byte_lines(data: bytes) -> str:
    values = [f"0x{value:02x}" for value in data]
    return "\n".join(
        "    " + ", ".join(values[index : index + 16]) + ","
        for index in range(0, len(values), 16)
    )


def deterministic_gzip(source: bytes) -> bytes:
    compressed = bytearray(gzip.compress(source, compresslevel=9, mtime=0))
    # Python 3.11/3.12 may copy zlib's platform-specific OS byte, while 3.13+
    # writes 255. The field does not affect decompression, so normalize it.
    compressed[9] = 255
    return bytes(compressed)


def build_assets(sources: dict[str, bytes]) -> tuple[tuple[str, str, bytes], ...]:
    index = sources["index.html"].decode("utf-8")
    for name in SCRIPT_NAMES:
        index = index.replace(f'    <script src="/{name}" defer></script>\n', "")
    index = index.replace(
        "  </body>",
        '    <script src="/meshscope-bundle.js" defer></script>\n  </body>',
    )
    bundle = b"\n;\n".join(sources[name] for name in SCRIPT_NAMES)
    return (
        ("index.html", "text/html; charset=utf-8", index.encode("utf-8")),
        ("styles.css", "text/css; charset=utf-8", sources["styles.css"]),
        ("meshscope-bundle.js", "application/javascript; charset=utf-8", bundle),
    )


def render() -> str:
    blocks: list[str] = []
    entries: list[str] = []
    source_hash = hashlib.sha256()
    sources = {name: (WEB_ROOT / name).read_bytes() for name in SOURCE_NAMES}
    for name in SOURCE_NAMES:
        source = sources[name]
        source_hash.update(name.encode("utf-8") + b"\0" + source)
    assets = build_assets(sources)
    for name, content_type, source in assets:
        compressed = deterministic_gzip(source)
        ident = symbol(name)
        blocks.append(
            f"inline constexpr uint8_t {ident}[] = {{\n"
            f"{byte_lines(compressed)}\n"
            f"}};\n"
        )
        path = "/" if name == "index.html" else f"/{name}"
        entries.append(
            f'    {{"{path}", "{content_type}", {ident}, sizeof({ident})}},'
        )

    return f"""// Generated by tools/generate_esp32_meshscope_assets.py. Do not edit.
#pragma once

#include <stddef.h>
#include <stdint.h>

namespace meshscope_web_assets {{

inline constexpr char SOURCE_SHA256[] = "{source_hash.hexdigest()}";

struct Asset {{
  const char *path;
  const char *content_type;
  const uint8_t *data;
  size_t size;
}};

{"".join(blocks)}
inline constexpr Asset ASSETS[] = {{
{chr(10).join(entries)}
}};
inline constexpr size_t ASSET_COUNT = sizeof(ASSETS) / sizeof(ASSETS[0]);

}}  // namespace meshscope_web_assets
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when the generated header does not match the web sources",
    )
    args = parser.parse_args()
    output = render()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != output:
            print(f"{OUTPUT} is stale; regenerate it.", file=sys.stderr)
            raise SystemExit(1)
        print(f"{OUTPUT} is current.")
        return
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(output, encoding="utf-8")
    print(f"Generated {OUTPUT} with 3 gzip assets.")


if __name__ == "__main__":
    main()
